[workspace]
authors = ["avcopan <avcopan@gmail.com>"]
channels = ["conda-forge"]
name = "mechtools"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build-pac99 = "cd PAC99 && pixi build"
build-thermp = "cd ThermP && pixi build"
build-projrot = "cd ProjRot && pixi build"
build-slatec = "cd SLATEC && pixi build"
build = { depends-on = ["build-pac99", "build-thermp", "build-projrot", "build-slatec"] }
upload-pac99 = "pixi run rattler-build upload anaconda -o Auto-Mech PAC99/*.conda || true"
upload-thermp = "pixi run rattler-build upload anaconda -o Auto-Mech ThermP/*.conda || true"
upload-projrot = "pixi run rattler-build upload anaconda -o Auto-Mech ProjRot/*.conda || true"
upload-slatec = "pixi run rattler-build upload anaconda -o Auto-Mech SLATEC/*.conda || true"
upload = { depends-on = ["upload-pac99", "upload-thermp", "upload-projrot", "upload-slatec"] }

[dependencies]
rattler-build = ">=0.47.0,<0.48"
