[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]
preview = ["pixi-build"]

[dependencies]
projrot = { path = "." }

[tasks]
test = "cp -r examples test-examples && cd test-examples/ch2oc6h4ch3 && projrot"

[package]
name = "projrot"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "0.3.*" }
