[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]
preview = ["pixi-build"]

[dependencies]
pac99 = { path = "." }

[tasks]
test = "cp -r examples test-examples && cd test-examples/ch4 && bash run_pac99.sh"

[package]
name = "pac99"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "0.3.*" }
