[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]
preview = ["pixi-build"]

[dependencies]
thermp = { path = "." }

[tasks]
test = "cp -r examples test-examples && cd test-examples/c5h7 && thermp"

[package]
name = "thermp"
version = "0.7.0"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "0.3.*" }
